name: Branch Protection

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

jobs:
  enforce-checks:
    name: Enforce Required Checks
    runs-on: ubuntu-latest
    
    steps:
    - name: Check PR Requirements
      run: |
        echo "🔒 Enforcing branch protection rules for main branch"
        echo "📋 Required checks:"
        echo "  ✓ All tests must pass"
        echo "  ✓ Security scan must complete"
        echo "  ✓ Code quality checks must pass"
        echo "  ✓ Build verification must succeed"
        echo "  ✓ At least one approval required"
        
    - name: Validate PR Title
      run: |
        PR_TITLE="${{ github.event.pull_request.title }}"
        echo "Validating PR title: $PR_TITLE"
        
        # Check if PR title starts with conventional commit type
        case "$PR_TITLE" in
          feat:*|fix:*|docs:*|style:*|refactor:*|test:*|chore:*)
            echo "✅ PR title follows conventional commit format"
            ;;
          feat\(*|fix\(*|docs\(*|style\(*|refactor\(*|test\(*|chore\(*)
            echo "✅ PR title follows conventional commit format with scope"
            ;;
          *)
            echo "❌ PR title must follow format: type(scope): description"
            echo "   Examples:"
            echo "   - feat: add hash validation"
            echo "   - fix(tests): resolve null pointer exception"
            echo "   - docs: update README"
            echo "   Current title: $PR_TITLE"
            exit 1
            ;;
        esac
        
    - name: Check PR Description
      run: |
        PR_BODY="${{ github.event.pull_request.body }}"
        if [ -z "$PR_BODY" ]; then
          echo "❌ PR description is required"
          echo "   Please provide:"
          echo "   - What changes were made"
          echo "   - Why the changes were necessary"
          echo "   - How to test the changes"
          exit 1
        else
          echo "✅ PR description provided"
        fi